echo "rectangle";
echo "length and breadth";
read l;
read b;
area=$(echo "$l*$b"|bc);
echo "area="$area;
echo "square";
echo "side";
read l;
area=$(echo "$l*$l"|bc);
echo "area="$area;
echo "circle";
echo "radius";
read r;
area=$(echo "3.14*($r*$r)"|bc);
echo "area="$area;
echo "circle";
echo "radius";
read r;
circum=$(echo "2*(3.14*$r)"|bc);
echo "circumference"$circum;
echo "triangle";
echo "length and base";
read l;
read b;
area=$(echo "0.5*($l*$b)"|bc);
echo "area="$area;
